version: '3'
services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdata2:/var/lib/mysql
    networks:
      - mynet2
  authenticationDBMigration:
    image: authentificationdb
    environment:
      - DATABASE_URL=authenticationDB

    networks:
      - mynet2
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB

    ports:
      - 5002:5002
    networks:
      - mynet2

  electionDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdata1:/var/lib/mysql
    networks:
      - mynet
  electionDbMigration:
    image: electiondbmigrations
    environment:
      - DATABASE_URL=electionDatabase

    networks:
      - mynet
  redis:
    image: redis
    ports:
      - 6379:6379
  user:
    image: user
    environment:
      - DATABASE_URL=electionDatabase

    ports:
      - 5004:5004
    networks:
      - mynet
  admin:
    image: admin
    environment:
      - DATABASE_URL=electionDatabase

    ports:
      - 5003:5003
    networks:
      - mynet
  deamon:
    image: deamon
    environment:
      - DATABASE_URL=electionDatabase
    networks:
      - mynet
    ports:
      - 5005:5005



volumes:
  dbdata2:
  dbdata1:

networks:
  mynet:
      driver: overlay
  mynet2:
      driver: overlay